version: "3.8"

services:
  ##
  # LDAP server
  #
  openldap:
    image: osixia/openldap
    env_file: openldap.env
    volumes:
      - "config:/etc/ldap/slapd.d/"
      - "data:/var/lib/ldap/"
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - node.hostname == web
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.phpldapadmin-tls.redirectscheme.scheme: "https"

        traefik.http.routers.phpldapadmin.rule: "Host(`ldap.dejonckhee.re`)"
        traefik.http.routers.phpldapadmin.entrypoints: "web"
        traefik.http.routers.phpldapadmin.middlewares: "phpldapadmin-tls"

        traefik.http.routers.phpldapadmin-tls.rule: "Host(`ldap.dejonckhee.re`)"
        traefik.http.routers.phpldapadmin-tls.entrypoints: "websecure"
        traefik.http.routers.phpldapadmin-tls.tls: "true"
        traefik.http.routers.phpldapadmin-tls.tls.certresolver: "letsencrypt"

        traefik.http.services.phpldapadmin.loadbalancer.server.port: "80"
        traefik.docker.network: "traefik_proxy"

volumes:
  config:
  data:

networks:
  proxy:
    external: true
    name: "traefik_proxy"
